version: "3"
services:
    db:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5432:5432
        environment:
            PGUSER: "postgres"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    postgres-data:
